<?php

namespace Sistema\FotocopiadoraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SucursalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SucursalRepository extends EntityRepository
{
}
