parameters:
#    msjinterna.example.class: Sistema\MsjinternaBundle\Example

services:
#    msjinterna.example:
#        class: %msjinterna.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
