<?php

namespace Sistema\PedidoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PedidocabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidocabRepository extends EntityRepository
{
    public function findByPedido($cuenta)
    {
        $query = $this->getEntityManager()->createQuery(
        'SELECT pcb.total
        FROM PedidoBundle:Pedidocab pcb, UsuariosBundle:Alumno ua
        WHERE ua.nrocuenta = :nrocuenta and ua.id = pcb.usuarioalu and pcb.estadopag = 1 '
        )->setParameter('nrocuenta', $cuenta);

        $pedido = $query->getResult();
        return $pedido;        
    }
}
