<?php

namespace Sistema\PedidoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PedidodetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidodetRepository extends EntityRepository
{
   public function FindByPedDet($id)
    {
        $query = $this->getEntityManager()->createQuery(
        'SELECT s
           FROM PedidoBundle:Pedidodet s
           WHERE s.Pedidocab =:idcab'
        )->setParameter('idcab', $id);

        $lineas = $query->getResult();
        return $lineas;        
    }
    
    public function findOneByIdJoinPedApu($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
            'SELECT p, a FROM PedidoBundle:Pedidodet pd
            JOIN pd.apunte a
            WHERE pd.id = :id'
        )->setParameter('id', $id);
        
        $pedidodet = $query->getResult();
        return $pedidodet;
    }    
}
