parameters:
#    facultad.example.class: Sistemag\FacultadBundle\Example

services:
#    facultad.example:
#        class: %facultad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
