<?php

namespace Sistema\UsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InformacionperfilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformacionperfilesRepository extends EntityRepository
{
}
