<?php

namespace Sistema\UsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InformacionperfilprofesorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformacionperfilprofesorRepository extends EntityRepository
{
}
