<?php

namespace Sistema\UsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoUsuarioRepository extends EntityRepository
{
    public function tipousuario1()
    {        
         $query = $this->getEntityManager()->createQuery(
        'SELECT t FROM UsuariosBundle:TipoUsuario t WHERE t.estado = 1 '
        );

        $emtity = $query->getResult();
        return $emtity;       
    }
 
    public function clavetipousuario($tipou)
    {        
         $query = $this->getEntityManager()->createQuery(
        'SELECT t.id FROM UsuariosBundle:TipoUsuario t WHERE t.name =:name'
        )->setParameter('name', $tipou);

        $tipousuario = $query->getResult();
        return $tipousuario;       
    }
}
