parameters:
#    fotocopiadora.example.class: Sistemagf\FotocopiadoraBundle\Example

#services:
#    login2_listener:
#        class: Sistemagf\FotocopiadoraBundle\Listener\Login2Listener 
#        arguments: ['@security.context', '@router']
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login }
#            - { name: kernel.event_listener, event: kernel.response }