<?php

namespace Sistema\FacultadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarreraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarreraRepository extends EntityRepository
{
    public function FindBycarrera($id)
    {
        $query = $this->getEntityManager()->createQuery(
        'SELECT s
           FROM FacultadBundle:Carrera s
          WHERE s.Facultad =:Fac_Codigo'
        )->setParameter('Fac_Codigo', $id);

        $carrera = $query->getResult();
        return $carrera;        
    }
    public function FindBycarreramateria($id)
    {
        $query = $this->getEntityManager()->createQuery(
        'SELECT m.CarreraMateria
        FROM FacultadBundle:Carrera m
        WHERE m.Carr_Codigo =:Carr_Codigo'
        )->setParameter('Carr_Codigo', $id);

        $materia = $query->getResult();
        return $materia;        
    }
}
