<?php

namespace Sistema\FacultadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacultadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultadRepository extends EntityRepository
{
    public function findByFacNombre($nomfac)
    {
        $query = $this->getEntityManager()->createQuery(
        'SELECT m.Fac_Codigo
        FROM FacultadBundle:Facultad m
          WHERE m.Fac_Nombre LIKE :Fac_Nombre'
        )->setParameter('Fac_Nombre', $nomfac);

        $facultad = $query->getResult();
        return $facultad; 
    }
}
