<?php

namespace Sistema\FacultadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MateriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriaRepository extends EntityRepository
{
//    public function FindBymateria($id)
//    {
//        $query = $this->getEntityManager()->createQuery(
//        'SELECT m
//        FROM FacultadBundle:Materia m '
//        );
//
//        $materia = $query->getResult();
//        return $materia;        
//    }
    
//    public function FindBymateria($id)
//    {
//        $query = $this->getEntityManager()->createQuery(
//        " select c, m
//        from FacultadBundle:Carrera c
//         left join c.Materia m
//        where c.Carr_Codigo=:Carr_Codigo"
//        )->setParameter('Carr_Codigo', $id);

//       " SELECT c, m
//        FROM FacultadBundle:Carrera c
//        LEFT JOIN c.Materia m
//        GROUP BY user.id");
        
        
//        $materia = $query->getResult();
//        return $materia;        
//    }    
}


